// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

// export const categories = [
//     'business',
//     'entertainment',
//     'general',
//     'health',
//     'science',
//     'sports',
//     'technology',
// ] as const;
// export type Category = typeof categories[number];

export interface NewsResponse {
    status: string;
    totalResults: number;
    articles: Article[];
}

export interface Article {
    source: Source;
    author: null | string;
    title: string;
    description: null | string;
    url: string;
    urlToImage: null | string;
    publishedAt: string;
    content: null | string;
}

export interface Source {
    id: null | string;
    name: string;
}

export interface ShownArticles {
    [key: string]: {
        page: number,
        articles: Article[],
    }
}